### Successful request
POST http://localhost:8000/api/contract/analysis
Content-Type: application/json

{
  "content": "This is a sample contract content for analysis."
}

### Get error message
POST http://localhost:8000/api/contract/analysis
Content-Type: application/json

{
  "content": 1531
}

### use ollama to analyze contract v1
POST http://localhost:8000/api/contract/analysis
Content-Type: application/json

{
  "contract": "The employer may terminate the employee’s contract at any time without prior notice or compensation."
}